name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. v0.1.2 or 0.1.2)"
        required: true
        type: string
      prerelease:
        description: "Mark as pre-release?"
        required: false
        default: false
        type: boolean

permissions:
  contents: write

env:
  GO_VERSION: 1.25.1
  GOLANGCI_LINT_VERSION: v2.4.0

jobs:
  version-bump-check:
    name: Version bump check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Version bump check vs latest FINAL tag
        shell: bash
        run: |
          set -euo pipefail

          RAW_INPUT="${{ github.event.inputs.version }}"
          RAW_INPUT="${RAW_INPUT## }"; RAW_INPUT="${RAW_INPUT%% }"   # trim just in case
          INPUT_NO_V="${RAW_INPUT#v}"

          # Accept SemVer with optional pre-release/+build; capture base X.Y.Z and optional rc number if present
          if [[ "$INPUT_NO_V" =~ ^([0-9]+(\.[0-9]+){2})(-rc\.?([0-9]+))?([+][0-9A-Za-z\.-]+)?$ ]]; then
            BASE_VERSION="${BASH_REMATCH[1]}"   # X.Y.Z
          else
            echo "::error::Input must be SemVer like 0.1.2, 1.2.3-rc.1, or v1.2.3"
            exit 1
          fi

          # Latest FINAL tag strictly vX.Y.Z (ignore prereleases)
          LATEST_FINAL_TAG=$(git tag --list 'v[0-9]*' \
            | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -V | tail -n1 || true)
          LATEST_FINAL_TAG=${LATEST_FINAL_TAG:-v0.0.0}
          OLD_FINAL_VERSION=${LATEST_FINAL_TAG#v}

          echo "Latest FINAL tag: $LATEST_FINAL_TAG"
          echo "Requested base:   $BASE_VERSION (from input: $RAW_INPUT)"

          # Require strictly newer than latest FINAL
          if [[ "$(printf '%s\n' "$OLD_FINAL_VERSION" "$BASE_VERSION" | sort -V | tail -n1)" != "$BASE_VERSION" ]]; then
            echo "::error::Requested $BASE_VERSION must be greater than latest final $OLD_FINAL_VERSION"
            exit 1
          fi

          echo "OK: $OLD_FINAL_VERSION → $BASE_VERSION"

  release:
    name: Test, tag & release
    needs: [version-bump-check]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: -v

      - name: Run tests (-race)
        shell: bash
        run: go test -mod=readonly ./... -count=1 -race

      - name: Compute tag (final or next -rc.N from input)
        id: compute_tag
        shell: bash
        run: |
          set -euo pipefail

          PRERELEASE="${{ github.event.inputs.prerelease }}"
          RAW_INPUT="${{ github.event.inputs.version }}"
          INPUT_NO_V="${RAW_INPUT#v}"

          # Parse input: base X.Y.Z and optional rc number if provided
          if [[ "$INPUT_NO_V" =~ ^([0-9]+(\.[0-9]+){2})(-rc\.?([0-9]+))?([+][0-9A-Za-z\.-]+)?$ ]]; then
            BASE_VERSION="${BASH_REMATCH[1]}"
            RC_NUM="${BASH_REMATCH[4]:-}"
          else
            echo "::error::Input must be SemVer like 0.1.2, 1.2.3-rc.1, or v1.2.3"
            exit 1
          fi

          final_exists() { git rev-parse "v${BASE_VERSION}" >/dev/null 2>&1; }

          next_rc_tag() {
            local base="$1"
            local maxn
            maxn=$(git tag --list "v${base}-rc*" \
              | sed -E 's/^.*-rc\.?([0-9]+)$/\1/' \
              | grep -E '^[0-9]+$' \
              | sort -n | tail -n1 || true)
            if [[ -z "${maxn:-}" ]]; then
              echo "v${base}-rc.1"
            else
              echo "v${base}-rc.$((maxn+1))"
            fi
          }

          # If a final already exists for this base, block both prerelease and final
          if final_exists; then
            if [[ "$PRERELEASE" == "true" ]]; then
              echo "::error::Cannot create prerelease: final tag v${BASE_VERSION} already exists"
            else
              echo "::error::Final tag v${BASE_VERSION} already exists; choose a higher version"
            fi
            exit 1
          fi

          if [[ "$PRERELEASE" == "true" ]]; then
            if [[ -n "${RC_NUM}" ]]; then
              # Honor explicit -rc.N if provided in input
              TAG="v${BASE_VERSION}-rc.${RC_NUM}"
            else
              TAG="$(next_rc_tag "$BASE_VERSION")"
            fi
            IS_PRE="true"
          else
            TAG="v${BASE_VERSION}"
            IS_PRE="false"
          fi

          # Final guard: do not reuse an existing tag
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "::error::Tag $TAG already exists"
            exit 1
          fi

          echo "version=$BASE_VERSION"      >> "$GITHUB_OUTPUT"
          echo "tag=$TAG"                   >> "$GITHUB_OUTPUT"
          echo "is_prerelease=$IS_PRE"      >> "$GITHUB_OUTPUT"

          echo "Computed tag: $TAG (prerelease=$IS_PRE)"

      - name: Create Git tag
        shell: bash
        run: |
          set -euo pipefail
          TAG="${{ steps.compute_tag.outputs.tag }}"
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists; skipping tag creation."
          else
            git tag -a "$TAG" -m "chore(release): $TAG"
            git push origin "$TAG"
          fi

      - name: Find previous final tag (-rc.N excluded)
        id: prev_final
        shell: bash
        run: |
          set -euo pipefail
          PREV=$(git tag --list 'v[0-9]*' \
            | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -V | tail -n2 | head -n1 || true)
          echo "prev=$PREV" >> "$GITHUB_OUTPUT"

      - name: Generate changelog (RC)
        id: git-cliff-rc
        if: ${{ steps.compute_tag.outputs.is_prerelease == 'true' }}
        uses: orhun/git-cliff-action@v4
        with:
          args: --current --no-exec
        env:
          GITHUB_REPO:  ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Generate changelog (final release)
        id: git-cliff-final
        if: ${{ steps.compute_tag.outputs.is_prerelease == 'false' }}
        uses: orhun/git-cliff-action@v4
        with:
          # If no previous final tag, this produces an empty range; optionally
          # fall back to the root commit if you want *all* history instead.
          args: "${{ steps.prev_final.outputs.prev }}..${{ steps.compute_tag.outputs.tag }} --no-exec"
        env:
          GITHUB_REPO:  ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name:   ${{ steps.compute_tag.outputs.tag }}
          name:       jsonrpc ${{ steps.compute_tag.outputs.tag }}
          body:       ${{ steps.compute_tag.outputs.is_prerelease == 'true'
                          && steps.git-cliff-rc.outputs.content
                          || steps.git-cliff-final.outputs.content }}
          prerelease: ${{ steps.compute_tag.outputs.is_prerelease }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
